config/routes.rb
Rails.application.routes.draw do
  scope "/admin" do
    resources :users
  end
  devise_for :users
  root to: 'professionals#index'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel-all', action: 'cancel_all'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'appointmentsGrid', to: 'exports#new', as: 'appointmentsGrid'
  post 'export_appointments', to: 'exports#export_appointments', as: 'export_appointments'
end

app/models/professional.rb
class Professional < ApplicationRecord
  has_many :appointments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20}

  def to_s
    name
  end

  def cancel_all
    self.appointments.where("date > ?", DateTime.now).destroy_all
  end

end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_professional, only: %i[ show edit update destroy ]

  # GET /professionals or /professionals.json
  def index
    @professionals = Professional.order(:name)
  end

  # GET /professionals/1 or /professionals/1.json
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals or /professionals.json
  def create
    @professional = Professional.new(professional_params)

    if @professional.save
      redirect_to @professional, notice: "Professional was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /professionals/1 or /professionals/1.json
  def update
    if @professional.update(professional_params)
      redirect_to @professional, notice: "Professional was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /professionals/1 or /professionals/1.json
  def destroy
    if @professional.destroy
      message = "Professional was successfully destroyed."
    else
      message = @professional.errors.full_messages.to_sentence
    end
    redirect_to professionals_url, notice: message
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_professional
    @professional = Professional.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def professional_params
    params.require(:professional).permit(:name)
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professionals/edit.html.erb
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

app/views/professionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Professionals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.name %></td>
        <td><%= link_to 'Show', professional %></td>
        <% if can? :update, professional %>
          <td><%= link_to 'Edit', edit_professional_path(professional) %></td>
        <% end %>
        <% if can? :destroy, professional %>
          <td><%= link_to 'Destroy', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Professional %>
  <%= link_to 'New Professional', new_professional_path %>
<% end %>
<%= link_to 'Users Administration', users_path %>
<%= link_to 'Export appointments', appointmentsGrid_path%>

app/views/professionals/new.html.erb
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Professional data </h1>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>

<%= link_to 'Appointments', professional_appointments_path(@professional) %> |
<%= link_to 'Back', professionals_path %>