config/routes.rb
Rails.application.routes.draw do
  scope "/admin" do
    resources :users
  end
  devise_for :users
  root to: 'professionals#index'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel-all', action: 'cancel_all'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'appointmentsGrid', to: 'exports#new', as: 'appointmentsGrid'
  post 'export_appointments', to: 'exports#export_appointments', as: 'export_appointments'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional
  validates :name, :surname, :phone, :date, presence: true
  validates :notes, length: { maximum: 50}
  validates :phone, numericality: { only_integer: true }
  validates :date, uniqueness: {scope: :professional_id}

  validate :valid_date, :after_today?

  def valid_date
    if !(self.date.min == 0 || self.date.min == 30)
      errors.add :date, 'El horario debe ser cada media hora'
    end
  end

  def after_today?
    if self.date < DateTime.now
      errors.add :date, 'La fecha no puede ser menor a hoy'
    end
  end

  def get_hour
    date.strftime("%H:%M")
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_professional
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = @professional.appointments.order(:date)
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = @professional.appointments.new(appointment_params)
      if @appointment.save
        redirect_to [@professional, @appointment], notice: "Appointment was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    if @appointment.update(appointment_params)
      redirect_to [@professional, @appointment], notice: "Appointment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    if @appointment.destroy
      message = "Appointment was successfully cancelled."
    else
      message = @appointment.errors.full_messages.to_sentence
    end
    redirect_to professional_appointments_path(@professional), notice: message
  end

  def cancel_all
    @professional.cancel_all
    redirect_to professional_appointments_path(@professional), notice: "Appointments successfully cancelled."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = @professional.appointments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :name, :surname, :phone, :notes)
    end

   def set_professional
    @professional = Professional.find(params[:professional_id])
   end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model:  [@professional, appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', professional_appointments_path(@professional) %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Professional</th>
      <th>Date</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Phone</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= @professional %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.surname %></td>
        <td><%= appointment.phone %></td>
        <td><%= appointment.notes %></td>
        <td><%= link_to 'Show', [@professional, appointment] %></td>
        <% if can? :update, appointment %>
          <td><%= link_to 'Edit', edit_professional_appointment_path(@professional, appointment) %></td>
        <% end %>
        <% if can? :destroy, appointment %>
          <td><%= link_to 'Cancel', [@professional, appointment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Back', @professional %>
<% if can? :create, Appointment %>
  <%= link_to 'New Appointment', new_professional_appointment_path(@professional) %>
<% end %>
<% if can? :cancel_all, Appointment %>
  <p><%= link_to 'Cancel all', cancel_all_professional_appointments_path(@professional), method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', professional_appointments_path(@professional) %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<%= link_to 'Back', professional_appointments_path(@professional) %>
<% if can? :update, Appointment %>
  <%= link_to 'Edit', edit_professional_appointment_path(@appointment) %> |
<% end %>