config/routes.rb
Rails.application.routes.draw do
  scope "/admin" do
    resources :users
  end
  devise_for :users
  root to: 'professionals#index'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'cancel-all', action: 'cancel_all'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'appointmentsGrid', to: 'exports#new', as: 'appointmentsGrid'
  post 'export_appointments', to: 'exports#export_appointments', as: 'export_appointments'
end

app/models/export.rb
class Export
  include ActiveModel::Validations
  include ActiveModel::Model

  attr_accessor :professional, :date, :type

  validates :date, :type, presence: true
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  load_and_authorize_resource

  def new
    @professionals = Professional.order(:name)
    @export = Export.new
  end

  def export_appointments
    @export = Export.new(exports_params)
    if @export.valid?
      exportAppointment = ExportAppointment.new()
      unless exports_params[:professional].blank?
        @professional = Professional.find(@export.professional)
      end
      if @export.type == "Dia"
        exportAppointment.export_appointments_day(@export.date, @professional)
        date = @export.date
      else
        exportAppointment.export_appointments_week(@export.date, @professional)
        date = @export.date.to_date.at_beginning_of_week
      end
      send_file(Rails.root.join("tmp/appointments_of_#{date}.html"))
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def exports_params
    params.require(:form_data).permit(:professional, :date, :type)
  end
end

app/views/exports/_form.html.erb
<%= form_for :form_data, url: export_appointments_path do |form| %>
  <div class="field">
    <%= form.label :professional %>
    <%= form.collection_select :professional, Professional.order(:name), :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type, ["Dia", "Semanal"] %>
  </div>

  <div class="actions">
    <%= submit_tag "Exportar", data: {disable_with: false} %>
  </div>

<% end %>

app/views/exports/new.html.erb
<h1>Export appointments</h1>

<%= render 'form', professionals: @professionals, export: @export %>
<%= link_to 'Back', professionals_path %>